### ISSUE TITLE
LICENSE and NOTICE file need to updated to respect original TLSH LICENSE

### ISSUE THREAD

**Issue by jonjoliver** [idealista/tlsh-js#15]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

The LICENSE is incorrect - it needs to be the original LICENSE file from
https://github.com/trendmicro/tlsh/blob/master/LICENSE
The NOTICE file from https://github.com/trendmicro/tlsh/blob/master/NOTICE.txt has been removed. The Apache LICENSE requires that the NOTICE file be kept.

### Steps to Reproduce

Read the LICENSE file here
Read the LICENSE file at https://github.com/trendmicro/tlsh/blob/master/LICENSE

### Versions

all

### Additional Information

see above

**Comment by dortegau** [comment]
As we consider that the project has diverged enough that none of the original author's code remain, we won't follow your recommendations. For ethical reasons we have mantained all references to TrendMicro and that references won't be removed. 

This project benefits greatly from the original library (basically to understand how it works), but never used its code.

Best regards.
